version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: curso_db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - curso-net
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: ${PROFILE:-prod}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/curso_db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - curso-net

networks:
  curso-net:

volumes:
  db_data:
